#!/usr/bin/env bash
set -eux

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "${NB_PYTHON_PREFIX}/share/jupyter/lab/settings"
cp "${SCRIPT_DIR}/overrides.json" \
  "${NB_PYTHON_PREFIX}/share/jupyter/lab/settings/overrides.json"
